In [1]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Dataset 2.csv to Dataset 2 (1).csv

In [5]:
df = pd.read_csv('Dataset 2.csv')

## Part A: Dataset Understanding

## Q1. Load the dataset and display the first five records.

In [6]:
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

## Q2. Determine the number of rows and columns in the dataset

In [7]:
df.shape

(750, 10)

## Q3. Display all column names.

In [8]:
df.columns

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

## Q4. Identify numerical and categorical features.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UserID               750 non-null    int64
 1   Age                  750 non-null    int64
 2   Gender               750 non-null    object
 3   SubscriptionType     750 non-null    object
 4   WatchHoursPerWeek    750 non-null    int64
 5   DevicesUsed          750 non-null    int64
 6   FavoriteGenre        750 non-null    object
 7   AdClicks             750 non-null    int64
 8   MonthlySpend         750 non-null    int64
 9   SubscriptionRenewed  750 non-null    object
dtypes: int64(6), object(4)
memory usage: 58.7+ KB

In [10]:
numerical = df.select_dtypes(include=['int64','float64'])
categorical = df.select_dtypes(include=['object'])

print("Numerical Columns:")
print(numerical.columns)

print("\nCategorical Columns:")
print(categorical.columns)

Numerical Columns:
Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')

Categorical Columns:
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

## Q5. Check whether the dataset contains missing values.

In [11]:
df.isnull().sum()

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

## Part B: Exploratory Data Analysis

## Q6. Calculate the average age of users.

In [12]:
df['Age'].mean()

np.float64(41.824)

## Q7. Determine the average watch hours per week.

In [13]:
df['WatchHoursPerWeek'].mean()

np.float64(14.236)

## Q8. Find the average monthly spending of users.

In [14]:
df['MonthlySpend'].mean()

np.float64(689.9053333333334)

## Q9. Count the number of users in each subscription category.

In [15]:
df['SubscriptionType'].value_counts()

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

## Q10. Determine the percentage of users who renewed their subscriptions.

In [16]:
(df['SubscriptionRenewed'].value_counts(normalize=True))*100

SubscriptionRenewed
No     53.733333
Yes    46.266667
Name: proportion, dtype: float64

## Part C: Data Preparation

## Q11. Convert categorical features into numerical form.

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])
df['SubscriptionType'] = le.fit_transform(df['SubscriptionType'])
df['FavoriteGenre'] = le.fit_transform(df['FavoriteGenre'])
df['SubscriptionRenewed'] = le.fit_transform(df['SubscriptionRenewed'])

## Q12. Define the feature set (X) and target variable (y) for subscription renewal prediction.

In [18]:
X = df.drop(['SubscriptionRenewed','UserID'], axis=1)

y = df['SubscriptionRenewed']

## Q13. Split the dataset into training and testing sets.

In [19]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42
)

## Part D: Decision Tree Classification

## Q14. Train a Decision Tree model to predict whether a user will renew their subscription.

In [20]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt.fit(X_train,y_train)

DecisionTreeClassifier()

## Q15. Evaluate the model using accuracy.

In [21]:
from sklearn.metrics import accuracy_score

y_pred = dt.predict(X_test)

accuracy_score(y_test,y_pred)

0.5533333333333333

## Q16. Generate and interpret the confusion matrix.

In [22]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)

print(cm)

[[45 37]
 [30 38]]

## Part E: K-Nearest Neighbors (KNN)

## Q17. Train a KNN classifier with K = 5.

In [23]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,y_train)

knn_pred = knn.predict(X_test)

## Q18. Compare the accuracy of KNN with the Decision Tree model.

In [24]:
knn_acc = accuracy_score(y_test,knn_pred)

print("Decision Tree:",accuracy_score(y_test,y_pred))
print("KNN:",knn_acc)

Decision Tree: 0.5533333333333333
KNN: 0.6333333333333333

## Part F: Linear Regression

## Q19. Train a Linear Regression model to predict monthly spending.

In [25]:
X = df.drop(['MonthlySpend','UserID'], axis=1)

y = df['MonthlySpend']

In [26]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42
)

In [27]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train,y_train)

LinearRegression()

## Q20. Predict the monthly spending for a new user and interpret the result.

In [28]:
new_user = [[25,1,2,15,2,1,10,0]]

prediction = lr.predict(new_user)

print(prediction)

[1321.77980632]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(